disabled_rules:
  - identifier_name
  - nesting
  - force_cast
  - function_parameter_count
  - todo
  - closure_parameter_position
opt_in_rules:
  - control_statement
  - empty_count
  - colon
  - comma
excluded:
  - Source/Resources/R.generated.swift
analyzer_rules:
  - explicit_self

force_try:
  severity: warning
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 800
large_tuple:
  - 3
  - 4
type_name:
  min_length: 4
  max_length:
    warning: 30
    error: 35
reporter: "xcode"
